export interface NJClub {
  code: string;
  name: string;
}

export const NJ_CLUBS: NJClub[] = [
  { code: 'AAST', name: 'All American Swim Team' },
  { code: 'ABSC', name: 'Absegami Swim Club' },
  { code: 'ACST', name: 'AC Stingrays' },
  { code: 'AQST', name: 'Aqua Storm' },
  { code: 'AQUA', name: 'Aquatic Club of NJ' },
  { code: 'ARMY', name: 'Army West Point Aquatics' },
  { code: 'BACK', name: 'Backbone Aquatics' },
  { code: 'BCSC', name: 'Bergen County Swim Club' },
  { code: 'BGCA', name: 'Boys & Girls Club of America' },
  { code: 'BGNJ', name: 'Badger Aquatics' },
  { code: 'BLST', name: 'Blazing Stars' },
  { code: 'BRSC', name: 'Bridgewater-Raritan Swim Club' },
  { code: 'CBSC', name: 'Caldwell Bluefish Swim Club' },
  { code: 'CCAQ', name: 'Cape-Atlantic Aquatics' },
  { code: 'CDSC', name: 'Cedar Grove Swim Club' },
  { code: 'CGSC', name: 'Colts Neck Green Swim Club' },
  { code: 'CMAC', name: 'Central Morris Aquatic Club' },
  { code: 'CNYB', name: 'Clifton YMCA Blue Dolphins' },
  { code: 'COND', name: 'Condors Swim Club' },
  { code: 'CRSC', name: 'Cresskill Swim Club' },
  { code: 'CSRJ', name: 'Chatham Silver Raiders' },
  { code: 'CVSC', name: 'Cherry Valley Swim Club' },
  { code: 'DARK', name: 'Dark Horses Aquatics' },
  { code: 'DCSC', name: 'Deptford Community Swim Club' },
  { code: 'DMST', name: 'Dynamo Swim Team' },
  { code: 'EAGL', name: 'Eagles Swim Club' },
  { code: 'EAST', name: 'Eastern Express Swim Club' },
  { code: 'EDKN', name: 'Edison Kings' },
  { code: 'ELSC', name: 'Egg Harbor Township Swim Club' },
  { code: 'EMST', name: 'Essex Marlins Swim Team' },
  { code: 'FAST', name: 'Fort Lee Aquatics Swim Team' },
  { code: 'FCSC', name: 'Franklin Community Swim Club' },
  { code: 'FISH', name: 'Fisher\'s Island Swim Club' },
  { code: 'FKSC', name: 'Fort Kids Swim Club' },
  { code: 'FREE', name: 'Freehold YMCA Swim Club' },
  { code: 'FROG', name: 'Frogs Swim Club' },
  { code: 'FRSC', name: 'Freehold Raceway Swim Club' },
  { code: 'GATO', name: 'Gato Swim Club' },
  { code: 'GSSC', name: 'Garden State Swim Club' },
  { code: 'GTSC', name: 'Greater Trenton Swim Club' },
  { code: 'HAST', name: 'Hasbrouck Heights Aquatic Club' },
  { code: 'HAWK', name: 'Hawk Swim Club' },
  { code: 'HISC', name: 'High Impact Swim Club' },
  { code: 'HMST', name: 'Hamilton Masters' },
  { code: 'HTSC', name: 'High Tech Swim Club' },
  { code: 'HVAC', name: 'Hudson Valley Aquatic Club' },
  { code: 'JERS', name: 'Jersey Gators' },
  { code: 'JSCA', name: 'Jersey Shore Competitive Aquatics' },
  { code: 'JSST', name: 'Jersey Shore Swim Team' },
  { code: 'KING', name: 'Kings Swim Club' },
  { code: 'KSRT', name: 'Kingsway Regional Swim Team' },
  { code: 'LGAC', name: 'Lakewood Aquatic Club' },
  { code: 'LISC', name: 'Livingston Swim Club' },
  { code: 'LKSC', name: 'Lakeview Swim Club' },
  { code: 'LMSC', name: 'Lakeland Hills YMCA Swim Club' },
  { code: 'LSSA', name: 'Little Silver Swim Association' },
  { code: 'MAKO', name: 'Makos Swim Club' },
  { code: 'MASC', name: 'Martinsville Swim Club' },
  { code: 'MBAQ', name: 'Montclair Backyard Aquatics' },
  { code: 'MBSC', name: 'Morristown-Beard Swim Club' },
  { code: 'MCAC', name: 'Morris County Aquatic Club' },
  { code: 'MEDC', name: 'Medford Swim Club' },
  { code: 'MFSC', name: 'Millburn-Fanwood Swim Club' },
  { code: 'MGSC', name: 'Mendham-Gladstone Swim Club' },
  { code: 'MOSC', name: 'Montclair Swim Club' },
  { code: 'MRST', name: 'Morris Rapids Swim Team' },
  { code: 'MSSC', name: 'Maplewood Swim Club' },
  { code: 'NAAC', name: 'North Arlington Aquatic Club' },
  { code: 'NBAC', name: 'North Bergen Aquatic Club' },
  { code: 'NJAC', name: 'New Jersey Aquatic Club' },
  { code: 'NJSC', name: 'New Jersey Swim Club' },
  { code: 'OCSC', name: 'Ocean County Swim Club' },
  { code: 'OAKS', name: 'Oaks Swim Club' },
  { code: 'OTSC', name: 'Otter Swim Club' },
  { code: 'PARS', name: 'Parsippany Area Racers' },
  { code: 'PAST', name: 'Panthers Swim Team' },
  { code: 'PBSC', name: 'Pine Barrens Swim Club' },
  { code: 'PISC', name: 'Piscataway Aquatic Club' },
  { code: 'PJSC', name: 'Pompton Junction Swim Club' },
  { code: 'PNAC', name: 'Princeton National Aquatic Club' },
  { code: 'PTSC', name: 'Pequannock Township Swim Club' },
  { code: 'RAQC', name: 'Ridgewood Aquatic Club' },
  { code: 'RAST', name: 'Raritan Swim Team' },
  { code: 'RCAT', name: 'Ridgewood Club Aquatic Team' },
  { code: 'RISC', name: 'Ridgefield Swim Club' },
  { code: 'RLAC', name: 'Ramapo-Lakeland Aquatic Club' },
  { code: 'RMSC', name: 'Ridge Marlboro Swim Club' },
  { code: 'ROCK', name: 'Rockaway River Country Club' },
  { code: 'RRSC', name: 'Raritan River Swim Club' },
  { code: 'SAIL', name: 'Sailfish Swim Club' },
  { code: 'SASC', name: 'South Amboy Swim Club' },
  { code: 'SCNJ', name: 'Swim Club New Jersey' },
  { code: 'SEAL', name: 'Seals Swim Club' },
  { code: 'SEAS', name: 'Seasons Swim Club' },
  { code: 'SESC', name: 'Shore Swim' },
  { code: 'SHRK', name: 'Sharks Swim Club' },
  { code: 'SHSC', name: 'Shrewsbury Swim Club' },
  { code: 'SNKR', name: 'Sneakers Swim Team' },
  { code: 'SPAR', name: 'Sparta Swim Team' },
  { code: 'SPRT', name: 'Sprint Aquatics' },
  { code: 'SSNJ', name: 'Shore Seagulls' },
  { code: 'STAR', name: 'Stars Swim Club' },
  { code: 'STSC', name: 'Stingrays Swim Club' },
  { code: 'SURF', name: 'Surf City Swim Club' },
  { code: 'SWSC', name: 'Summit West Swim Club' },
  { code: 'TCAT', name: 'Tri-County Aquatics' },
  { code: 'TESC', name: 'Tenafly Swim Club' },
  { code: 'TIDE', name: 'Tide Swim Club' },
  { code: 'UNAT', name: 'Unattached' },
  { code: 'VMSC', name: 'Verona-Montclair Swim Club' },
  { code: 'WAVE', name: 'Wave Swim Club' },
  { code: 'WNAC', name: 'Wayne National Aquatic Club' },
  { code: 'WSSC', name: 'West Shore Swim Club' },
  { code: 'YMCA', name: 'YMCA Swim Team' },
].sort((a, b) => a.name.localeCompare(b.name));
