export interface NJClub {
  code: string;
  name: string;
}

export const NJ_CLUBS: NJClub[] = [
  { code: 'ACE',  name: 'ACE Swim Team' },
  { code: 'APEX', name: 'APEX Predators' },
  { code: 'BAC',  name: 'Berkeley Aquatic Club' },
  { code: 'BB',   name: 'Bergen Barracuda Swim Club' },
  { code: 'BGH',  name: 'Brigantine Green Heads Swim Team' },
  { code: 'BWTD', name: 'JCC Bridgewater Tide' },
  { code: 'CAT',  name: 'Cougar Aquatic Team' },
  { code: 'CBGC', name: 'Clifton Boys & Girls Club Seahawks' },
  { code: 'CJAC', name: 'Central Jersey Aquatic Club' },
  { code: 'DESC', name: 'Deep End Aquatics Swim Club' },
  { code: 'EAG',  name: 'Eagle Aquatic Club' },
  { code: 'EGBC', name: 'Escualos of BGC Paterson & Passaic' },
  { code: 'EEX',  name: 'Eastern Express Swim Team' },
  { code: 'ESC',  name: 'Elite Swim Club' },
  { code: 'FSPY', name: 'Fanwood Scotch Plains YMCA' },
  { code: 'GMY',  name: 'Greater Morristown YMCA' },
  { code: 'GSCY', name: 'Greater Somerset County YMCA Storm' },
  { code: 'HACY', name: 'Hamilton YMCA Aquatic Club' },
  { code: 'HCY',  name: 'Hunterdon County YMCA' },
  { code: 'HQH',  name: 'Healthquest Hammerheads Swim Team' },
  { code: 'JAC',  name: 'Jersey Aquatic Club' },
  { code: 'JFAC', name: 'Jersey Flyers Aquatic Club' },
  { code: 'JG',   name: 'Jersey Gator Swim Club' },
  { code: 'JSY',  name: 'YMCA of the Jersey Shore' },
  { code: 'LHY',  name: 'Lakeland Hills Family YMCA' },
  { code: 'LIFE', name: 'Metro Area Lifetime Swimming' },
  { code: 'MAY',  name: 'Madison Area YMCA Mariners' },
  { code: 'MB',   name: 'Monmouth Barracudas' },
  { code: 'MDY',  name: 'Meadowlands YMCA Sharks' },
  { code: 'MEY',  name: 'Metuchen-Edison YMCA Manta Rays' },
  { code: 'MYM',  name: 'Montclair YMCA Dolphins' },
  { code: 'NJB',  name: 'North Jersey Barracudas' },
  { code: 'NJBL', name: 'North Jersey Bluestreaks' },
  { code: 'NJRC', name: 'New Jersey Race Club' },
  { code: 'NJSD', name: 'NJ Sea Dragons' },
  { code: 'OCY',  name: 'Ocean County YMCA Tigersharks' },
  { code: 'OTT',  name: 'Sea Ott Swim Team' },
  { code: 'PAA',  name: 'Peddie Aquatic Association' },
  { code: 'PPST', name: 'Princeton Piranhas Swim Team' },
  { code: 'PRIN', name: 'Princeton University' },
  { code: 'PTAC', name: 'Princeton Tigers Aquatic Club' },
  { code: 'RSA',  name: 'Rebel Aquatic Club' },
  { code: 'RVYM', name: 'Raritan Valley YMCA Riptide' },
  { code: 'RY',   name: 'Ridgewood YMCA Breakers' },
  { code: 'SAY',  name: 'Summit Area YMCA Seals' },
  { code: 'SCAR', name: 'Scarlet Aquatics' },
  { code: 'SCY',  name: 'Sussex County YMCA' },
  { code: 'STAC', name: 'Streamline Aquatics Club' },
  { code: 'STAR', name: 'Star Aquatic Club' },
  { code: 'SWST', name: 'Sea Wolves Swim Team' },
  { code: 'TAC',  name: 'Genesis Riptide Swim Team' },
  { code: 'TWST', name: 'Tidal Wave Swim Team' },
  { code: 'UNAT', name: 'Unattached' },
  { code: 'WAKE', name: 'Wavemakers' },
  { code: 'WAVE', name: 'Waverunners' },
  { code: 'WFY',  name: 'Wyckoff YMCA Sharks' },
  { code: 'WMY',  name: 'West Morris Area YMCA' },
  { code: 'WW',   name: 'Whitewaters Swimming' },
  { code: 'WWAT', name: 'Water Warriors Aquatic Team' },
  { code: 'WY',   name: 'Westfield YMCA' },
  { code: 'XCEL', name: 'X-Cel Swimming' },
].sort((a, b) => a.name.localeCompare(b.name));
